name: Danger

on:
    - pull_request

jobs:
    danger:
        name: Danger

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Danger
              uses: danger/danger-js@10.5.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # https://github.com/danger/danger-js/issues/557#issuecomment-664851950
                  DANGER_DISABLE_TRANSPILATION: true
